### ISSUE TITLE
Update Django version

### ISSUE THREAD

**Issue by DanteOnline** [libresource/pygenesis-django#3]
**Is your feature request related to a problem? Please describe.**
Current django version not secure

**Describe the solution you'd like**
- install latest Django version
- run tests
- update `requirements.txt`

**Comment by imprvhub** [comment]
hi @DanteOnline can i be assigned to contribute to this issue? Thanks!

**Comment by DanteOnline** [comment]
> hi @DanteOnline can i be assigned to contribute to this issue? Thanks!

Yes, of course. You are welcome.

**Comment by imprvhub** [comment]
Hi @DanteOnline! 🙂 Sorry for the slight delay in getting this done - it's been quite a busy start to my week! I've just submitted the PR with the updates as requested:

Updated Django to the latest secure version (5.1.4)
Added more robust tests to verify Django's core functionality
Everything's passing and working smoothly

Please let me know if you'd like me to make any adjustments to the changes. Thanks again for letting me contribute! 🙌

**Comment by DanteOnline** [comment]
@imprvhub , no problem. Any time is good. Thanks
